# Generated by Django 4.1.5 on 2023-01-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
        ('core', '0007_auto_20200510_2016'),
    ]

    operations = [
    ]
